name: Tests
on:
  push:
    branches: [ dev-Test ]
  pull_request:
    branches: [ dev-Test ]

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: nathanheffley/laravel-phpunit-action@master
